standingsrequests/urls.py
from django.urls import path

from .views import (
    admin,
    create_requests,
    effective_requests,
    manage_requests,
    standings,
)

app_name = "standingsrequests"

urlpatterns = [
    # index
    path("", create_requests.index_view, name="index"),
    # admin
    path(
        "admin_changeset_update_now/",
        admin.admin_changeset_update_now,
        name="admin_changeset_update_now",
    ),
    # create_requests
    path("create_requests", create_requests.create_requests, name="create_requests"),
    path(
        "request_characters",
        create_requests.request_characters,
        name="request_characters",
    ),
    path(
        "request_corporations",
        create_requests.request_corporations,
        name="request_corporations",
    ),
    path(
        "request_character_standing/<int:character_id>/",
        create_requests.request_character_standing,
        name="request_character_standing",
    ),
    path(
        "remove_character_standing/<int:character_id>/",
        create_requests.remove_character_standing,
        name="remove_character_standing",
    ),
    path(
        "request_corp_standing/<int:corporation_id>/",
        create_requests.request_corp_standing,
        name="request_corp_standing",
    ),
    path(
        "remove_corp_standing/<int:corporation_id>/",
        create_requests.remove_corp_standing,
        name="remove_corp_standing",
    ),
    path("manage/setuptoken/", create_requests.view_auth_page, name="view_auth_page"),
    path(
        "requester_add_scopes/",
        create_requests.view_requester_add_scopes,
        name="view_requester_add_scopes",
    ),
    # effective requests
    path(
        "view/requests/",
        effective_requests.effective_requests,
        name="effective_requests",
    ),
    path(
        "view/requests/data/",
        effective_requests.effective_requests_data,
        name="effective_requests_data",
    ),
    # manage requests
    path("manage/", manage_requests.manage_standings, name="manage"),
    path(
        "manage/requests/",
        manage_requests.manage_requests_list,
        name="manage_requests_list",
    ),  # Should always follow the path of the GET path above
    path(
        "manage/requests/<int:contact_id>/",
        manage_requests.manage_requests_write,
        name="manage_requests_write",
    ),
    path(
        "manage/revocations/",
        manage_requests.manage_revocations_list,
        name="manage_revocations_list",
    ),
    path(
        "manage/revocations/<int:contact_id>/",
        manage_requests.manage_revocations_write,
        name="manage_revocations_write",
    ),
    # Standings
    path("standings", standings.standings, name="standings"),
    path(
        "standings/characters/data",
        standings.character_standings_data,
        name="character_standings_data",
    ),
    path(
        "standings/characters/download",
        standings.download_pilot_standings,
        name="download_pilots",
    ),
    path(
        "standings/corporations/data",
        standings.corporation_standings_data,
        name="corporation_standings_data",
    ),
    path(
        "standings/alliances/data",
        standings.alliance_standings_data,
        name="alliance_standings_data",
    ),
]

standingsrequests/views/create_requests.py
from typing import Set

from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.html import format_html
from django.utils.translation import gettext_lazy as _
from esi.decorators import token_required
from esi.models import Token
from eveuniverse.models import EveEntity

from allianceauth.eveonline.models import EveCharacter
from allianceauth.services.hooks import get_extension_logger
from app_utils.logging import LoggerAddTag

from standingsrequests import __title__
from standingsrequests.app_settings import SR_CORPORATIONS_ENABLED
from standingsrequests.constants import CreateCharacterRequestResult
from standingsrequests.core import app_config
from standingsrequests.decorators import token_required_by_state
from standingsrequests.helpers.evecorporation import EveCorporation
from standingsrequests.models import ContactSet, StandingRequest, StandingRevocation
from standingsrequests.tasks import update_all, update_associations_api

from ._common import DEFAULT_ICON_SIZE, add_common_context

logger = LoggerAddTag(get_extension_logger(__name__), __title__)


@login_required
@permission_required(StandingRequest.REQUEST_PERMISSION_NAME)
def index_view(request):
    """index page is used as dispatcher"""
    app_count = (
        StandingRequest.objects.pending_requests().count()
        + StandingRevocation.objects.pending_requests().count()
    )
    if app_count > 0 and request.user.has_perm("standingsrequests.affect_standings"):
        return redirect("standingsrequests:manage")

    return redirect("standingsrequests:create_requests")


@login_required
@permission_required(StandingRequest.REQUEST_PERMISSION_NAME)
def create_requests(request):
    organization = app_config.standings_source_entity()
    try:
        main_char_id = request.user.profile.main_character.character_id
    except AttributeError:
        main_char_id = None

    image_url = organization.icon_url(size=DEFAULT_ICON_SIZE) if organization else ""
    context = {
        "corporations_enabled": SR_CORPORATIONS_ENABLED,
        "organization": organization,
        "organization_image_url": image_url,
        "authinfo": {"main_char_id": main_char_id},
    }
    return render(
        request,
        "standingsrequests/create_requests.html",
        add_common_context(request, context),
    )


@login_required
@permission_required(StandingRequest.REQUEST_PERMISSION_NAME)
def request_characters(request):
    logger.debug("Start request_characters request")
    try:
        contact_set = ContactSet.objects.latest()
    except ContactSet.DoesNotExist:
        return render(
            request, "standingsrequests/error.html", add_common_context(request, {})
        )

    eve_characters = _make_eve_characters_map(request)
    characters_with_standing = {
        contact["eve_entity_id"]: contact["standing"]
        for contact in (
            contact_set.contacts.filter(
                eve_entity_id__in=list(eve_characters.keys())
            ).values("eve_entity_id", "standing")
        )
    }
    characters_standings_requests = {
        obj.contact_id: obj
        for obj in (
            StandingRequest.objects.select_related("user")
            .filter(contact_id__in=eve_characters.keys())
            .annotate_is_pending()
            .annotate_is_actioned()
        )
    }
    characters_standing_revocation = {
        obj.contact_id: obj
        for obj in (
            StandingRevocation.objects.filter(
                contact_id__in=eve_characters.keys()
            ).annotate_is_pending()
        )
    }
    characters_data = [
        _create_character_row(
            user=request.user,
            character=character,
            characters_with_standing=characters_with_standing,
            characters_standings_requests=characters_standings_requests,
            characters_standing_revocation=characters_standing_revocation,
        )
        for character in eve_characters.values()
    ]

    context = {"characters": characters_data}
    return render(
        request,
        "standingsrequests/partials/request_characters.html",
        add_common_context(request, context),
    )


def _create_character_row(
    user: User,
    character: EveCharacter,
    characters_with_standing,
    characters_standings_requests,
    characters_standing_revocation,
):
    character_id = character.character_id
    standing = characters_with_standing.get(character_id)
    has_pending_request = (
        character_id in characters_standings_requests
        and characters_standings_requests[character_id].is_pending_annotated
    )
    has_pending_revocation = (
        character_id in characters_standing_revocation
        and characters_standing_revocation[character_id].is_pending_annotated
    )
    has_actioned_request = (
        character_id in characters_standings_requests
        and characters_standings_requests[character_id].is_actioned_annotated
    )
    has_standing = (
        character_id in characters_standings_requests
        and characters_standings_requests[character_id].is_effective
        and characters_standings_requests[character_id].user == user
    )
    result = {
        "character": character,
        "standing": standing,
        "pendingRequest": has_pending_request,
        "pendingRevocation": has_pending_revocation,
        "requestActioned": has_actioned_request,
        "inOrganisation": app_config.is_character_a_member(character),
        "hasRequiredScopes": StandingRequest.has_required_scopes_for_request(
            character, user=user, quick_check=True
        ),
        "hasStanding": has_standing,
    }
    return result


def _make_eve_characters_map(request):
    eve_characters_qs = EveCharacter.objects.filter(
        character_ownership__user=request.user
    ).select_related("character_ownership__user")
    eve_characters = {obj.character_id: obj for obj in eve_characters_qs}
    return eve_characters


@login_required
@permission_required(StandingRequest.REQUEST_PERMISSION_NAME)
def request_corporations(request):
    logger.debug("Start request_characters request")
    try:
        contact_set = ContactSet.objects.latest()
    except ContactSet.DoesNotExist:
        return render(
            request, "standingsrequests/error.html", add_common_context(request, {})
        )

    corporation_ids = _calc_corporation_ids(request.user)
    corporations_standing_requests = {
        obj.contact_id: obj
        for obj in (
            StandingRequest.objects.select_related("user")
            .filter(contact_id__in=corporation_ids)
            .annotate_is_pending()
            .annotate_is_actioned()
        )
    }
    corporations_revocation_requests = {
        obj.contact_id: obj
        for obj in (
            StandingRevocation.objects.filter(contact_id__in=corporation_ids)
            .annotate_is_pending()
            .annotate_is_actioned()
        )
    }
    corporation_contacts = {
        obj.eve_entity_id: obj
        for obj in (contact_set.contacts.filter(eve_entity_id__in=corporation_ids))
    }
    corporations_data = []
    for corporation in EveCorporation.get_many_by_id(corporation_ids):
        if not corporation or corporation.is_npc:
            continue

        row = _create_corporation_row(
            user=request.user,
            corporation=corporation,
            corporations_standing_requests=corporations_standing_requests,
            corporations_revocation_requests=corporations_revocation_requests,
            corporation_contacts=corporation_contacts,
        )
        corporations_data.append(row)

    corporations_data.sort(key=lambda x: x["corp"].corporation_name)
    context = {"corps": corporations_data}
    return render(
        request,
        "standingsrequests/partials/request_corporations.html",
        add_common_context(request, context),
    )


def _create_corporation_row(
    user: User,
    corporation: EveCorporation,
    corporations_standing_requests,
    corporations_revocation_requests,
    corporation_contacts,
):
    corporation_id = corporation.corporation_id
    try:
        standing = corporation_contacts[corporation_id].standing
    except KeyError:
        standing = None
    has_pending_request = (
        corporation_id in corporations_standing_requests
        and corporations_standing_requests[corporation_id].is_pending_annotated
    )
    has_pending_revocation = (
        corporation_id in corporations_revocation_requests
        and corporations_revocation_requests[corporation_id].is_pending_annotated
    )
    has_actioned_request = (
        corporation_id in corporations_standing_requests
        and corporations_standing_requests[corporation_id].is_actioned_annotated
    )
    has_standing = (
        corporation_id in corporations_standing_requests
        and corporations_standing_requests[corporation_id].is_effective
        and corporations_standing_requests[corporation_id].user == user
    )
    result = {
        "token_count": corporation.member_tokens_count_for_user(user, quick_check=True),
        "corp": corporation,
        "standing": standing,
        "pendingRequest": has_pending_request,
        "pendingRevocation": has_pending_revocation,
        "requestActioned": has_actioned_request,
        "hasStanding": has_standing,
    }

    return result


def _calc_corporation_ids(user: User) -> Set[int]:
    eve_characters_qs = EveCharacter.objects.filter(
        character_ownership__user=user
    ).select_related("character_ownership__user")
    corporation_ids = set(
        eve_characters_qs.exclude(corporation_id__in=app_config.corporation_ids())
        .exclude(alliance_id__in=app_config.alliance_ids())
        .values_list("corporation_id", flat=True)
    )

standingsrequests/views/effective_requests.py
from django.contrib.auth.decorators import login_required, permission_required
from django.db import models
from django.http import JsonResponse
from django.shortcuts import render
from django.utils.html import format_html
from django.views.decorators.cache import cache_page

from allianceauth.services.hooks import get_extension_logger
from app_utils.logging import LoggerAddTag

from standingsrequests import __title__
from standingsrequests.app_settings import SR_PAGE_CACHE_SECONDS
from standingsrequests.constants import DATETIME_FORMAT_PY
from standingsrequests.core import app_config
from standingsrequests.models import StandingRequest

from ._common import add_common_context, compose_standing_requests_data

logger = LoggerAddTag(get_extension_logger(__name__), __title__)


@login_required
@permission_required("standingsrequests.affect_standings")
def effective_requests(request):
    context = {
        "organization": app_config.standings_source_entity(),
        "requests_count": _standing_requests_to_view().count(),
    }
    return render(
        request,
        "standingsrequests/effective_requests.html",
        add_common_context(request, context),
    )


@cache_page(SR_PAGE_CACHE_SECONDS)
@login_required
@permission_required("standingsrequests.affect_standings")
def effective_requests_data(request):
    requests_data = compose_standing_requests_data(
        _standing_requests_to_view(), quick_check=True
    )
    for req in requests_data:
        req["request_date_str"] = {
            "display": req["request_date"].strftime(DATETIME_FORMAT_PY),
            "sort": req["request_date"].isoformat(),
        }
        req["labels_str"] = ", ".join(req["labels"])
        scopes_html = (
            '<i class="fas fa-check fa-fw text-success" title="Has required scopes"></i>'
            if req["has_scopes"]
            else '<i class="fas fa-times fa-fw text-danger" title="Does not have required scopes"></i>'
        )
        req["scopes_state_html"] = format_html(
            "{} {}", format_html(scopes_html), req["state"]
        )
        effective_html = (
            '<i class="fas fa-check fa-fw text-success" title="Standing Effective"></i>'
            if req["is_effective"]
            else '<i class="fas fa-times fa-fw text-danger" title="Standing not effective"></i>'
        )
        req["effective_html"] = format_html(
            "{} {}", format_html(effective_html), req["action_by"]
        )
        # remove columns that are not needed to reduce data volume
        del req["request_date"]
        del req["reason"]
        del req["main_character_ticker"]
        del req["main_character_icon_url"]
        del req["contact_icon_url"]
        del req["corporation_id"]
        del req["alliance_id"]
        del req["labels"]
        del req["is_effective"]
        del req["is_character"]
        del req["is_corporation"]
        del req["actioned"]
    return JsonResponse({"data": requests_data})


def _standing_requests_to_view() -> models.QuerySet:
    return (
        StandingRequest.objects.filter(is_effective=True)
        .select_related("user__profile")
        .order_by("-request_date")
    )

standingsrequests/templates/standingsrequests/_base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% load static %}

{% block page_title %}{% translate app_title %}{% endblock %}

{% block content %}
    <br>
    {% include 'standingsrequests/partials/menu.html' %}
    {% block details %}{% endblock %}
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'standingsrequests/css/global.css' %}" type="text/css" media="screen">
{% endblock extra_css %}

standingsrequests/templates/standingsrequests/create_requests.html
{% extends "standingsrequests/_base.html" %}
{% load static %}
{% load i18n %}

{% block details %}
    <h2>{% translate "My Requests" %}</h2>
    <p class="text-muted">
        {% blocktranslate with organization_name=organization.name %}
            On this page you can create requests to get standing or revoke standing with {{ organization_name }} for your alts.
            If you are missing an alt, please add it first on the dashboard.
        {% endblocktranslate %}
    </p>

    <ul id="myTabs" class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#tab-characters" aria-controls="tab-characters" role="tab" data-toggle="tab">
                {% translate "My Characters" %}
            </a>
        </li>
        {% if corporations_enabled %}
            <li role="presentation">
                <a href="#tab-corporations" aria-controls="tab-corporations" role="tab" data-toggle="tab">
                    {% translate "My Corporations" %}
                </a>
            </li>
        {% endif %}
    </ul>

    <div class="panel panel-default panel-tabs">
        <div class="panel-body">
            <div class="tab-content">

                <div role="tabpanel" class="tab-pane active" id="tab-characters">
                    <div hx-get="{% url 'standingsrequests:request_characters' %}" hx-trigger="load">
                        {% include "standingsrequests/partials/spinner.html" %}
                    </div>
                </div>

                {% if corporations_enabled %}
                    <div role="tabpanel" class="tab-pane" id="tab-corporations">
                        <div hx-get="{% url 'standingsrequests:request_corporations' %}" hx-trigger="load">
                            {% include "standingsrequests/partials/spinner.html" %}
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <br>
    <div class="panel panel-default">
        <div class="panel-heading">{% translate "Icon Legend" %}</div>
        <div class="panel-body">
            <table class="table">
                <tr>
                    <td>
                        <i class="fas fa-star fa-fw text-primary"></i>
                    </td>
                    <td>
                        {% translate "Character is in this organisation." %}
                    </td>
                </tr>
                <tr>
                    <td>
                        <i class="fas fa-exclamation-triangle fa-fw text-warning"></i>
                    </td>
                    <td>
                        {% translate "The character / corporation has no standings from this organisation towards it." %}
                    </td>
                </tr>
                <tr>
                    <td>
                        <i class="fas fa-hourglass-start fa-fw"></i>
                    </td>
                    <td>
                        {% translate "The standing has been requested and is pending action by a standings manager." %}
                    </td>
                </tr>
                <tr>
                    <td>
                        <i class="fas fa-hourglass-half fa-fw text-success"></i>
                    </td>
                    <td>
                        {% translate "The request has been accepted by a standings manager, but is waiting for confirmation that those standings have been updated in game." %}
                    </td>
                </tr>
                <tr>
                    <td>
                        <i class="fas fa-reply-all fa-fw text-danger"></i>
                    </td>
                    <td>
                        {% translate "The standing is being revoked by yourself, a standings manager or automatically if you no longer meet the requirements permitting blue standings access. It is pending confirmation." %}
                    </td>
                </tr>
                <tr>
                    <td>
                        <i class="fas fa-info-circle fa-fw text-info"></i>
                    </td>
                    <td>
                        {% translate "More keys are required to request standing for this corporation." %}
                    </td>
                </tr>
            </table>
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'standingsrequests/css/create_requests.css' %}" type="text/css" media="screen">
{% endblock extra_css %}

{% block extra_javascript %}
    {% include "standingsrequests/bundles/htmx.html" %}
    {% include "standingsrequests/bundles/helper-js.html" %}
    <script type="application/javascript">
        $(document).ready(function () {
            rememberLastTab('standingsrequests', 'create-requests', '#tab-characters')
        });
    </script>
{% endblock %}

standingsrequests/templates/standingsrequests/standings.html
{% extends "standingsrequests/_base.html" %}
{% load static %}
{% load i18n %}

{% block details %}

    <h2>{{ operation_mode|capfirst }} {% translate "Standings" %}</h2>

    <ul id="myTabs" class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#tab-characters" aria-controls="tab-characters" role="tab" data-toggle="tab">
                {% translate "Characters" %}
            </a>
        </li>
        <li role="presentation">
            <a href="#tab-corporations" aria-controls="tab-corporations" role="tab" data-toggle="tab">
                {% translate "Corporations" %}
            </a>
        </li>
        <li role="presentation">
            <a href="#tab-alliances" aria-controls="tab-alliances" role="tab" data-toggle="tab">
                {% translate "Alliances" %}
            </a>
        </li>
    </ul>

    <div class="panel panel-default panel-tabs">
        <div class="panel-body">
            <div class="tab-content">
                {% include "standingsrequests/partials/tab_character_standings.html" %}
                {% include "standingsrequests/partials/tab_corporation_standings.html" %}
                {% include "standingsrequests/partials/tab_alliance_standings.html" %}
            </div>
        </div>
    </div>
    <p class="text-muted">
        {% blocktranslate with organization_name=organization.name last_update=lastUpdate|timesince %}
            Current in-game contacts with standings for {{ organization_name }} •
            This data was last updated {{ last_update }} ago and is cached
        {% endblocktranslate %}
    </p>
    <!-- transfer data to javascript -->
    {{ show_mains|json_script:"show-mains-data" }}
{% endblock details %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
    {% include 'bundles/filterdropdown-js.html' %}
    {% include "standingsrequests/bundles/helper-js.html" %}
    <script type="application/javascript">

        /* renders standing columns for datatables */
        function renderStanding ( data, type, row ) {
            if ( type !== "display" ) {
                return data;
            }
            else {
                let symbol;
                let style;

                if (data < -5) {
                    symbol = "fas fa-minus-square fa-fw fa-lg";
                    style = "color:#930404;";
                } else if (data < 0) {
                    symbol = "fas fa-minus-square fa-fw fa-lg";
                    style = "color:#c34704;";
                } else if (data === 0) {
                    symbol = "fas fa-equals fa-fw fa-lg";
                    style = "background:#878787; color:white; font-size:75%";
                } else if (data <= 5) {
                    symbol = "fas fa-plus-square fa-fw fa-lg";
                    style = "color:#2a64c3;";
                } else {
                    symbol = "fas fa-plus-square fa-fw fa-lg";
                    style = "color:#042177;";
                }
                return `<i class="${symbol}" style="${style};" title="${data}"></i>`
            }
        }

        $(document).ready(function () {
            const showMains = JSON.parse(document.getElementById('show-mains-data').textContent);
            let columns = [
                {
                    data: 'character_name_html',
                    render: {
                        _: 'display',
                        sort: 'sort'
                    }
                },
                { data: 'corporation_name' },
                { data: 'alliance_name' },
                { data: 'faction_name' },
                {
                    data: 'standing',
                    render: renderStanding
                },
                { data: 'labels_str' },
            ];
            let columnDefs = null;
            let filterDropDownColumns = [
                {
                    idx: 1,
                    maxWidth: "15rem"
                },
                {
                    idx: 2,
                    maxWidth: "15rem"
                },
                {
                    idx: 3,
                    maxWidth: "15rem"
                },
                {
                    idx: 4,
                    maxWidth: "15rem"
                }
            ];
            if (showMains) {
                columns.push(
                    {
                        data: 'main_character_html',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: 'state' },
                    /* invisible columns */
                    { data: 'main_character_name' },
                );
                columnDefs = [
                    { "visible": false, "targets": [8] }
                ]
                filterDropDownColumns.push(
                    {
                        idx: 8,
                        title: "{% translate 'Main' %}",
                        maxWidth: "15rem"
                    },
                    {
                        idx: 7,
                        maxWidth: "15rem"
                    }
                )
            }
            $('#tbl-character-standings').DataTable({
                ajax: {
                    url: "{% url 'standingsrequests:character_standings_data' %}",
                    dataSrc: 'data',
                    cache: true
                },
                columns: columns,
                order: [[0, "asc"]],
                columnDefs: columnDefs,
                filterDropDown: {
                    columns: filterDropDownColumns,
                    autoSize: false,
                    bootstrap: true
                },
            });

            columns = [
                {
                    data: 'corporation_html',
                    render: {
                        _: 'display',
                        sort: 'sort'
                    }
                },
                { data: 'alliance_name' },
                { data: 'faction_name' },
                {
                    data: 'standing',
                    render: renderStanding
                },
                { data: 'labels_str' },
            ];
            columnDefs = null;
            filterDropDownColumns = [
                {
                    idx: 1,
                    maxWidth: "15rem"
                },
                {
                    idx: 2,
                    maxWidth: "15rem"
                },
                {
                    idx: 3,
                    maxWidth: "15rem"
                }
            ];
            if (showMains) {
                columns.push(
                    {
                        data: 'main_character_html',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: 'state' },
                    /* invisible columns */
                    { data: 'main_character_name' },
                );
                columnDefs = [
                    { "visible": false, "targets": [7] }
                ]
                filterDropDownColumns.push(
                    {
                        idx: 7,
                        title: "{% translate 'Main' %}",
                        maxWidth: "15rem"
                    },
                    {
                        idx: 6,
                        maxWidth: "15rem"
                    }
                )
            }
            $('#tbl-corporation-standings').DataTable({
                ajax: {
                    url: "{% url 'standingsrequests:corporation_standings_data' %}",
                    dataSrc: 'data',
                    cache: true
                },
                columns: columns,
                order: [[0, "asc"]],
                columnDefs: columnDefs,
                filterDropDown: {
                    columns: filterDropDownColumns,
                    autoSize: false,
                    bootstrap: true
                },
            });
            $('#tbl-alliance-standings').DataTable({
                ajax: {
                    url: "{% url 'standingsrequests:alliance_standings_data' %}",
                    dataSrc: 'data',
                    cache: true
                },
                columns: [
                    {
                        data: 'alliance_html',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    {
                        data: 'standing',
                        render: renderStanding
                    },
                    { data: 'labels_str' },
                ],
                order: [[0, "asc"]],
                filterDropDown: {
                    columns: [
                        {
                            idx: 1,
                            maxWidth: "15rem"
                        }
                    ],
                    autoSize: false,
                    bootstrap: true
                },
            });
            rememberLastTab('standingsrequests', 'standings', '#tab-characters');
        });
    </script>

{% endblock extra_javascript %}

{% block extra_css %}
    {{ block.super }}
    {% include 'bundles/datatables-css.html' %}
{% endblock extra_css %}