standingsrequests/urls.py
from django.urls import path

from .views import (
    admin,
    create_requests,
    effective_requests,
    manage_requests,
    standings,
)

app_name = "standingsrequests"

urlpatterns = [
    # index
    path("", create_requests.index_view, name="index"),
    # admin
    path(
        "admin_changeset_update_now/",
        admin.admin_changeset_update_now,
        name="admin_changeset_update_now",
    ),
    # create_requests
    path("create_requests", create_requests.create_requests, name="create_requests"),
    path(
        "request_characters",
        create_requests.request_characters,
        name="request_characters",
    ),
    path(
        "request_corporations",
        create_requests.request_corporations,
        name="request_corporations",
    ),
    path(
        "request_character_standing/<int:character_id>/",
        create_requests.request_character_standing,
        name="request_character_standing",
    ),
    path(
        "remove_character_standing/<int:character_id>/",
        create_requests.remove_character_standing,
        name="remove_character_standing",
    ),
    path(
        "request_corp_standing/<int:corporation_id>/",
        create_requests.request_corp_standing,
        name="request_corp_standing",
    ),
    path(
        "remove_corp_standing/<int:corporation_id>/",
        create_requests.remove_corp_standing,
        name="remove_corp_standing",
    ),
    path("manage/setuptoken/", create_requests.view_auth_page, name="view_auth_page"),
    path(
        "requester_add_scopes/",
        create_requests.view_requester_add_scopes,
        name="view_requester_add_scopes",
    ),
    # effective requests
    path(
        "view/requests/",
        effective_requests.effective_requests,
        name="effective_requests",
    ),
    path(
        "view/requests/data/",
        effective_requests.effective_requests_data,
        name="effective_requests_data",
    ),
    # manage requests
    path("manage/", manage_requests.manage_standings, name="manage"),
    path(
        "manage/requests/",
        manage_requests.manage_requests_list,
        name="manage_requests_list",
    ),  # Should always follow the path of the GET path above
    path(
        "manage/requests/<int:contact_id>/",
        manage_requests.manage_requests_write,
        name="manage_requests_write",
    ),
    path(
        "manage/revocations/",
        manage_requests.manage_revocations_list,
        name="manage_revocations_list",
    ),
    path(
        "manage/revocations/<int:contact_id>/",
        manage_requests.manage_revocations_write,
        name="manage_revocations_write",
    ),
    # Standings
    path("standings", standings.standings, name="standings"),
    path(
        "standings/characters/data",
        standings.character_standings_data,
        name="character_standings_data",
    ),
    path(
        "standings/characters/download",
        standings.download_pilot_standings,
        name="download_pilots",
    ),
    path(
        "standings/corporations/data",
        standings.corporation_standings_data,
        name="corporation_standings_data",
    ),
    path(
        "standings/alliances/data",
        standings.alliance_standings_data,
        name="alliance_standings_data",
    ),
]

standingsrequests/templates/standingsrequests/partials/manage_empty_row.html
{% load i18n %}

<tr>
    <td
        class="text-muted"
        colspan="9"
        style="text-align: left; vertical-align: middle;">
        {% translate "Empty" %}
    </td>
</tr>

standingsrequests/templates/standingsrequests/partials/manage_requests_list.html
{% load static %}
{% load i18n %}

<div class="table-responsive">
    <table id="tab_requests" class="table table-condensed table-hover table-striped">
        <thead>
            <tr>
                <th class="col-md-1">{% translate "Date" %}</th>
                <th class="col-md-2">{% translate "Contact Name" %}</th>
                <th class="col-md-2">{% translate "Organization" %}</th>
                <th class="col-md-2">{% translate "Main Character" %}</th>
                <th class="col-md-3">{% translate "Scopes / State" %}</th>
                <th class="col-md-2">{% translate "Actions" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for contact in requests %}
                <tr hx-target="this" hx-swap="delete">
                    <td>
                        {{ contact.request_date|date:DATETIME_FORMAT_HTML }}
                    </td>
                    <td>
                        <img src="{{ contact.contact_icon_url }}" class="img-circle"/>&nbsp;&nbsp;
                        <span class="copy_to_clipboard" data-text="{{ contact.contact_name }}">
                            {{ contact.contact_name }}&nbsp;<i class="far fa-copy"></i>
                        </span>
                    </td>
                    <td>
                        [{{ contact.corporation_ticker }}] {{ contact.corporation_name }}
                        <br>
                        {{ contact.alliance_name }}
                    </td>
                    <td>
                        <img src="{{ contact.main_character_icon_url }}" class="img-circle"/>&nbsp;&nbsp;
                        [{{ contact.main_character_ticker }}] {{ contact.main_character_name }}
                    </td>
                    <td>
                        {% if contact.has_scopes %}
                            <i class="fas fa-check fa-fw text-success" title="Has required scopes"></i>
                        {% else %}
                            <i class="fas fa-times fa-fw text-danger" title="Does not have required scopes"></i>
                        {% endif %}
                        {{contact.state}}
                    </td>
                    <td>
                        <button class="btn btn-success"
                                hx-put="{% url 'manage_requests_write' contact.contact_id %}"
                                title="{% translate 'Confirm the standing was ADDED in game' %}">
                            {% translate "Confirm" %}
                        </button>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <button class="btn btn-danger"
                                hx-confirm="{% translate 'Are you sure?' %}"
                                hx-delete="{% url 'manage_requests_write' contact.contact_id %}"
                                title="{% translate 'Reject this standing request' %}">
                            {% translate "Reject" %}
                        </button>
                    </td>
                </tr>
            {% empty %}
                {% include "standingsrequests/partials/manage_empty_row.html" %}
            {% endfor %}
        </tbody>
    </table>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $(".copy_to_clipboard").click(function(){
            const text = event.currentTarget.getAttribute("data-text");
            navigator.clipboard.writeText(text).then(function() {
                /* clipboard successfully set */
            }, function() {
                console.error("Failed to copy to clipboard");
            });
        });
    });
</script>

standingsrequests/templates/standingsrequests/partials/manage_revocations_list.html
{% load static %}
{% load i18n %}

<div class="table-responsive">
    <table id="tab_revocations" class="table table-condensed table-hover table-striped">
        <thead>
            <tr>
                <th class="col-md-1">{% translate "Date" %}</th>
                <th class="col-md-2">{% translate "Contact Name" %}</th>
                <th class="col-md-2">{% translate "Organization" %}</th>
                <th class="col-md-2">{% translate "Main Character" %}</th>
                <th class="col-md-1">{% translate "Scopes / State" %}</th>
                <th class="col-md-2">{% translate "Reason / Contact Labels" %}</th>
                <th class="col-md-2">{% translate "Actions" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for contact in revocations %}
                <tr hx-target="this" hx-swap="delete">
                    <td>
                        {{ contact.request_date|date:DATETIME_FORMAT_HTML }}
                    </td>
                    <td>
                        <img src="{{ contact.contact_icon_url }}" class="img-circle"/>&nbsp;&nbsp;
                        <span class="copy_to_clipboard" data-text="{{ contact.contact_name }}">
                            {{ contact.contact_name }}&nbsp;<i class="far fa-copy"></i>
                        </span>
                    </td>
                    <td>
                        [{{ contact.corporation_ticker }}] {{ contact.corporation_name }}
                        <br>
                        {{ contact.alliance_name }}
                    </td>
                    <td>
                        <img src="{{ contact.main_character_icon_url }}" class="img-circle"/>&nbsp;&nbsp;
                        [{{ contact.main_character_ticker }}] {{ contact.main_character_name }}
                    </td>
                    <td>
                        {% if contact.has_scopes %}
                            <i class="fas fa-check fa-fw text-success" title="Has required scopes"></i>
                        {% else %}
                            <i class="fas fa-times fa-fw text-danger" title="Does not have required scopes"></i>
                        {% endif %}
                        {{ contact.state }}
                    </td>
                    <td>
                        {{ contact.reason }}<br>
                        {{ contact.labels|join:", " }}
                    </td>
                    <td>
                        <button class="btn btn-success"
                                hx-put="{% url 'manage_revocations_write' contact.contact_id %}"
                                title="{% translate 'Confirm the standing was REMOVED in game' %}">
                            {% translate "Confirm" %}
                        </button>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <button class="btn btn-danger"
                                hx-confirm="{% translate 'Are you sure?' %}"
                                hx-delete="{% url 'manage_revocations_write' contact.contact_id %}"
                                title="{% translate 'Reject this revocation request' %}">
                            {% translate "Reject" %}
                        </button>
                    </td>
                </tr>
            {% empty %}
                {% include "standingsrequests/partials/manage_empty_row.html" %}
            {% endfor %}
        </tbody>
    </table>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $(".copy_to_clipboard").click(function(){
            const text = event.currentTarget.getAttribute("data-text");
            navigator.clipboard.writeText(text).then(function() {
                /* clipboard successfully set */
            }, function() {
                console.error("Failed to copy to clipboard");
            });
        });
    });
</script>

standingsrequests/templates/standingsrequests/partials/menu.html
{% load i18n %}
{% load navactive %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% translate "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'standingsrequests:index' %}">{{ app_title }}</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{% navactive request 'standingsrequests:create_requests' %}">
                    <a href="{% url 'standingsrequests:create_requests' %}">{% translate "My Requests" %}</a>
                </li>

                 {% if perms.standingsrequests.affect_standings %}
                <li class="{% navactive request 'standingsrequests:manage' %}">
                    <a href="{% url 'standingsrequests:manage' %}">
                        {% translate "Manage Requests" %}
                        {% if pending_total_count > 0 %}
                            &nbsp;<span class="badge badge-nav">{{ pending_total_count }}</span>
                        {% endif %}
                    </a>
                </li>
                {% endif %}

                <li class="{% navactive request 'standingsrequests:standings' %}">
                    <a href="{% url 'standingsrequests:standings' %}">
                        {{ operation_mode|capfirst }} {% translate "Standings" %}
                    </a>
                </li>

            </ul>
             <ul class="nav navbar-nav navbar-right">
                {% if perms.standingsrequests.affect_standings %}
                    <a class="btn btn-default navbar-btn" href="{% url 'standingsrequests:view_auth_page' %}">
                        {% if operation_mode == "corporation" %}
                            {% translate "Setup Corporation Token" %}
                        {% else %}
                            {% translate "Setup Alliance Token" %}
                        {% endif %}
                    </a>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

standingsrequests/templates/standingsrequests/partials/request_characters.html
{% load i18n %}
{% load evelinks %}

<div class="table-responsive">
    <table class="table table-hover table-striped table-width-fix" id="tbl-characters">
        <thead>
            <tr>
                <th>{% translate "Character" %}</th>
                <th>{% translate "Corporation" %}</th>
                <th>{% translate "Alliance" %}</th>
                <th>{% translate "Scopes" %}</th>
                <th>{% translate "Standing" %}</th>
                <th>{% translate "Actions" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for std in characters %}
                <tr>
                    <td>
                        <img src="{{ std.character|character_portrait_url:32 }}" class="img-circle">&nbsp;&nbsp;&nbsp;{{ std.character.character_name }}
                    </td>
                    <td>
                        [{{ std.character.corporation_ticker }}] {{ std.character.corporation_name }}
                    </td>
                    <td>
                        {{ std.character.alliance_name|default_if_none:"" }}
                    </td>
                    <td>
                        {% if std.hasRequiredScopes %}
                            <i class="fas fa-check fa-fw fa-lg text-success" title="Has required scopes"></i>
                        {% else %}
                            <a  title="{% translate 'Add required scopes' %}"
                                class="btn btn-danger btn-sm"
                                href="{% url 'standingsrequests:view_requester_add_scopes' %}">
                                <i class="fas fa-plus fa-fw fa-lg"></i> {% translate "Required" %}
                            </a>
                        {% endif %}
                    </td>
                    <td>
                        {% if std.inOrganisation == True %}
                            <i class="fas fa-star fa-fw fa-lg text-primary" title="{% translate 'In Organisation' %}"></i>
                        {% elif std.requestActioned == True %}
                            <i class="fas fa-hourglass-half fa-lg fa-fw text-success" title="{% translate 'Accepted, pending update in game.' %}"></i>
                        {% elif std.pendingRequest == True %}
                            <i class="fas fa-hourglass-start fa-lg fa-fw" title="{% translate 'Standing Pending' %}"></i>
                        {% elif std.pendingRevocation == True %}
                            <i class="fas fa-reply-all fa-fw fa-lg text-danger" title="{% translate 'Standing is being revoked' %}"></i>
                        {% elif std.standing == None and std.pendingRequest == False %}
                            <i class="fas fa-exclamation-triangle fa-lg text-warning" title="{% translate 'No Standing' %}"></i>
                        {% else %}
                            {% include 'standingsrequests/partials/standing_symbol.html' with standing=std.standing %}
                        {% endif %}
                    </td>
                    <td>
                        {% if std.inOrganisation == True %}
                            <!-- Already in organisation, No actions -->
                        {% elif std.pendingRequest == True or std.requestActioned == True %}
                            <a
                                class="btn btn-warning"
                                role="button"
                                href="{% url 'standingsrequests:remove_character_standing' character_id=std.character.character_id %}"
                                title="{% translate 'Cancel Request' %}">
                                {% translate "Cancel" %}
                            </a>
                        {% elif std.pendingRevocation == True %}
                            <!-- Revoked, No actions -->
                        {% elif not std.hasStanding %}
                            {% if std.hasRequiredScopes %}
                                <a
                                    class="btn btn-primary"
                                    role="button"
                                    href="{% url 'standingsrequests:request_character_standing' character_id=std.character.character_id %}"
                                    title="{% translate 'Request to get standing for this character' %}"
                                    >
                                    {% translate "Apply" %}
                                </a>
                            {% else %}
                                <button
                                    class="btn btn-primary"
                                    role="button"
                                    title="{% translate 'Missing scopes' %}" disabled>
                                    {% translate "Apply" %}
                                </button>
                            {% endif %}
                        {% else %}
                            <a
                                class="btn btn-danger"
                                role="button"
                                href="{% url 'standingsrequests:remove_character_standing' character_id=std.character.character_id %}"
                                title="{% translate 'Request to revoke standing for this character' %}">
                                {% translate "Revoke" %}
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

standingsrequests/templates/standingsrequests/partials/request_corporations.html
{% load static %}
{% load i18n %}
{% load evelinks %}


<div class="table-responsive">
    <table class="table table-hover table-striped table-width-fix" id="tbl-corporations">
        <thead>
            <tr>
                <th>{% translate "Corporation" %}</th>
                <th>{% translate "Alliance" %}</th>
                <th>{% translate "Keys/Req" %}</th>
                <th>{% translate "Standing" %}</th>
                <th>{% translate "Actions" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for st in corps %}
                <tr>
                    <td>
                        <img src="{{ st.corp.corporation_id|corporation_logo_url:32 }}" class="img-circle">
                        &nbsp;&nbsp;&nbsp;
                        {{ st.corp.corporation_name }}
                    </td>
                    <td>
                        {{ st.corp.alliance_name|default_if_none:"" }}
                    </td>
                    <td>
                        {{ st.token_count }}/{{ st.corp.member_count }}
                    </td>
                    <td>
                        {% if st.inOrganisation == True %}
                            <i class="fas fa-star fa-lg fa-fw text-primary" title="{% translate 'In Organisation' %}"></i>
                        {% elif st.requestActioned == True %}
                            <i class="fas fa-hourglass-half fa-lg fa-fw text-success" title="{% translate 'Accepted, pending update in game.' %}"></i>
                        {% elif st.pendingRequest == True %}
                            <i class="fas fa-hourglass-start fa-lg fa-fw" title="{% translate 'Standing Pending' %}"></i>
                        {% elif st.pendingRevocation == True %}
                            <i class="fas fa-reply-all fa-lg fa-fw text-danger" title="{% translate 'Standing is being revoked' %}"></i>
                        {% elif st.standing == None and st.pendingRequest == False %}
                            <i class="fas fa-exclamation-triangle fa-lg text-warning" title="{% translate 'No Standing' %}"></i>
                        {% else %}
                            {% include 'standingsrequests/partials/standing_symbol.html' with standing=st.standing %}
                        {% endif %}
                    </td>
                    <td>
                        {% if st.pendingRequest == True or st.requestActioned == True %}
                            <a
                                class="btn btn-warning"
                                role="button"
                                href="{% url 'standingsrequests:remove_corp_standing' corporation_id=st.corp.corporation_id %}"
                                title="{% translate 'Cancel Request' %}">
                                {% translate "Cancel" %}
                            </a>
                        {% elif st.pendingRevocation == True %}
                            <!-- Revoked, No actions -->
                        {% elif not st.hasStanding %}
                            {% if st.token_count >= st.corp.member_count %}
                                <a
                                    class="btn btn-primary"
                                    role="button"
                                    href="{% url 'standingsrequests:request_corp_standing' corporation_id=st.corp.corporation_id %}"
                                    title="{% translate 'Request to get standing for this corporation' %}">
                                    {% translate "Apply" %}
                                </a>
                            {% else %}
                                <i class="fas fa-info-circle fa-lg fa-fw text-info" title="{% translate 'More keys required to request standings' %}"></i>
                            {% endif %}
                        {% else %}
                            <a
                                class="btn btn-danger"
                                role="button"
                                href="{% url 'standingsrequests:remove_corp_standing' corporation_id=st.corp.corporation_id %}"
                                title="{% translate 'Request to revoke standing for this corporation' %}">
                                {% translate "Revoke" %}
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

standingsrequests/templates/standingsrequests/partials/spinner.html
{% load static %}
{% load i18n %}


{% if NIGHT_MODE %}
    <img src="{% static 'standingsrequests/img/Spinner-1s-64px-dark.gif' %}" alt="Spinner"/>
{% else %}
    <img src="{% static 'standingsrequests/img/Spinner-1s-64px-light.gif' %}" alt="Spinner"/>
{% endif %}
{% translate "Loading..." %}

standingsrequests/templates/standingsrequests/partials/standing_symbol.html
{% if standing < -5.0 %}
    <i class="fas fa-minus-square fa-lg fa-fw" style="color:#930404;" title="{{ standing }}"></i>
{% elif standing < 0.0 %}
    <i class="fas fa-minus-square fa-lg fa-fw" style="color:#c34704;" title="{{ standing }}"></i>
{% elif standing == 0.0 %}
    &nbsp;<i class="fas fa-equals fa-lg fa-fw" style="background:#878787; color:white; font-size:75%" title="{{ standing }}"></i>
{% elif standing <= 5.0 %}
    <i class="fas fa-plus-square fa-lg fa-fw" style="color:#2a64c3;" title="{{ standing }}"></i>
{% elif standing <= 10.0 %}
    <i class="fas fa-plus-square fa-lg fa-fw" style="color:#042177;" title="{{ standing }}"></i>
{% endif %}

standingsrequests/templates/standingsrequests/partials/tab_alliance_standings.html
{% load i18n %}

<div role="tabpanel" class="tab-pane" id="tab-alliances">
    <div class="table-responsive">
        <table id="tbl-alliance-standings" class="table table-striped table-width-fix">
            <thead>
                <tr>
                    <th class="col-md-6">{% translate "Name" %}</th>
                    <th class="col-md-1">{% translate "Standing" %}</th>
                    <th class="col-md-5">{% translate "Labels" %}</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

standingsrequests/templates/standingsrequests/partials/tab_character_standings.html
{% load i18n %}

<div role="tabpanel" class="tab-pane active" id="tab-characters">
    <div class="table-responsive">
        <table id="tbl-character-standings" class="table table-striped table-width-fix">
            <thead>
                <tr>
                    <th>{% translate "Name" %}</th>
                    <th>{% translate "Corporation" %}</th>
                    <th>{% translate "Alliance" %}</th>
                    <th>{% translate "Faction" %}</th>
                    <th>{% translate "Standing" %}</th>
                    <th>{% translate "Labels" %}</th>
                    {% if show_mains %}
                        <th>{% translate "Main Character" %}</th>
                        <th>{% translate "State" %}</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

standingsrequests/templates/standingsrequests/partials/tab_corporation_standings.html
{% load i18n %}

<div role="tabpanel" class="tab-pane" id="tab-corporations">
    <div class="table-responsive">
        <table id="tbl-corporation-standings" class="table table-striped table-width-fix">
            <thead>
                <tr>
                    <th class="col-md-2">{% translate "Name" %}</th>
                    <th class="col-md-2">{% translate "Alliance" %}</th>
                    <th class="col-md-2">{% translate "Faction" %}</th>
                    <th class="col-md-1">{% translate "Standing" %}</th>
                    <th class="col-md-2">{% translate "Labels" %}</th>
                    {% if show_mains %}
                        <th class="col-md-2">{% translate "Main Character" %}</th>
                        <th class="col-md-1">{% translate "State" %}</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

standingsrequests/templates/standingsrequests/partials/tbl_effective_requests.html
{% load i18n %}


<div class="table-responsive">
    <table id="tbl-effective-requests" class="table table-striped table-width-fix">
        <thead>
            <tr>
                <th>{% translate "Date" %}</th>
                <th>{% translate "Contact Name" %}</th>
                <th>{% translate "Organization" %}</th>
                <th>{% translate "Main Character" %}</th>
                <th>{% translate "Scopes / State" %}</th>
                <th>{% translate "Effective / Accepted By" %}</th>
                <th>{% translate "Contact Labels" %}</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>